apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  labels:
    app: wordpress
type: Opaque
data:
  # mot de passe : secret
  # echo "secret" | base64
  root-password: c2VjcmV0
  # login/mdp/db : wordpress
  db-name: d29yZHByZXNz
  db-login: d29yZHByZXNz
  db-password: d29yZHByZXNz
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-local
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-local
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db-login
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-local
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress-back
  labels:
    app: wordpress
    tier: backend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: backend
    spec:
      containers:
      - image: nazarpc/phpmyadmin
        name: phpmyadmin
        env:
        - name: MYSQL_HOST
          value: wordpress-mysql
        ports:
        - containerPort: 80
          name: phpmyadmin-port
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: wordpress
    tier: backend
spec:
  ports:
  - port: 32000
    nodePort: 32000
    targetPort: phpmyadmin-port
    protocol: TCP
  selector:
    app: wordpress
    tier: backend
  type: NodePort
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress-front
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db-login
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db-password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secrets
              key: db-name
        ports:
        - containerPort: 80
          name: wordpress-port
        volumeMounts:
        - name: wordpress-volume
          mountPath: /var/www/html
      volumes:
      - name: wordpress-volume
        persistentVolumeClaim:
          claimName: wordpress-local
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
    tier: frontend
spec:
  ports:
  - port: 31000
    nodePort: 31000
    targetPort: wordpress-port
    protocol: TCP
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
