apiVersion: v1
kind: Pod
metadata:
  name: basic-nginx
  labels:
    app: nginx
spec:
  nodeSelector:
    env: dev
  containers:
  - name: nginx-demo
    image: gcr.io/google_containers/echoserver:1.4
    ports:
    - name: nginx-port
      containerPort: 8080