apiVersion: v1
kind: Namespace
metadata:
  name: app-wordpress
  labels:
    app: app-wordpress
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: app-wordpress
  labels:
    app: wordpress
type: Opaque
data:
  # mot de passe : secret
  # echo "secret" | base64
  root-password: c2VjcmV0
  # login/mdp/db : wordpress
  db-name: d29yZHByZXNz
  db-login: d29yZHByZXNz
  db-password: d29yZHByZXNz
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-local
  namespace: app-wordpress
  labels:
    app: wordpress
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-local
  namespace: app-wordpress
  labels:
    app: wordpress
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: app-wordpress
  labels:
    app: wordpress
    tier: mysql
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
        - image: mysql:8
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: db-name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: db-login
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: db-password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-local
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: app-wordpress
  labels:
    app: wordpress
    tier: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-front
  namespace: app-wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - image: wordpress
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: db-login
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: db-password
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: db-name
          ports:
            - containerPort: 80
              name: wordpress-port
          volumeMounts:
            - name: wordpress-volume
              mountPath: /var/www/html             
      volumes:
        - name: wordpress-volume
          persistentVolumeClaim:
            claimName: wordpress-local
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: app-wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  selector:
    app: wordpress
  ports:
    - port: 31000
      targetPort: wordpress-port
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-back
  namespace: app-wordpress
  labels:
    app: wordpress
    tier: backend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: backend
    spec:
      containers:
        - image: nazarpc/phpmyadmin
          name: phpmyadmin
          env:
            - name: MYSQL_HOST
              value: wordpress-mysql
          ports:
            - containerPort: 80
              name: phpmyadmin-port
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 30
            periodSeconds: 30              
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 30
            periodSeconds: 30                 
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: app-wordpress
  labels:
    app: wordpress
    tier: backend
spec:
  selector:
    app: wordpress
  ports:
    - port: 32000
      targetPort: phpmyadmin-port
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-rules
  namespace: app-wordpress
spec:
  rules:
    - host: wordpress.evoliatis.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-service
                port:
                  number: 31000
    - host: phpmyadmin.evoliatis.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpmyadmin-service
                port:
                  number: 32000
