apiVersion: v1
kind: Secret
metadata:
  name: mysql-db
  labels:
    app: mysql    
type: Opaque
data:
  # valeur: secret
  password: c2VjcmV0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-local"
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /data/local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local
  labels:
    app: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql.evoliatis.fr
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mariadb:10.6
        name: mysql
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-db
              key: password
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: pvc-local
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql    
spec:
  ports:
  - port: 31400
    nodePort: 31400
    targetPort: mysql-port
    protocol: TCP
  selector:
    app: mysql
  type: NodePort
