apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stress
  name: stress
  labels:
    app: stress
spec:
  selector:
    matchLabels:
      app: stress
  replicas: 1
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: evoliatis/stress
        args:
          - -c
          - "1"
        resources:
          requests:
            cpu: "100m"
            memory: 16Mi
          limits:
            cpu: "250m"
            memory: 32Mi            
