apiVersion: v1
kind: Pod
metadata:
  name: mount.secret.evoliatis.fr
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: http-port
      containerPort: 80
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
      readOnly: false
  volumes:
  - name: secret-volume
    secret: 
      secretName: nginx-secrets
