apiVersion: v1
kind: Service
metadata:
  name: nginx-http
  labels:
    app: nginx  
spec:
  ports:
  - port: 31300
    nodePort: 31300
    targetPort: http-port
    protocol: TCP
  selector:
    app: nginx
  type: NodePort
