apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-local"
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /data/local
