kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-local
  labels:
    app: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
