apiVersion: v1
kind: Service
metadata:
  name: webservice-service
spec:
  ports:
  - port: 31004
    nodePort: 31004
    targetPort: webservice-port
    protocol: TCP
  selector:
    app: webservice
  type: NodePort
