apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # Mode Staging 
    server: https://acme-staging-v02.api.letsencrypt.org/directory    
    # Mode Production
    # server: https://acme-v02.api.letsencrypt.org/directory
    email: email@domaine.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx