apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-rules
  namespace: app-wordpress
spec:
  rules:
    - host: wordpress.k8s0.evoliatis.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-service
                port:
                  number: 31000
    - host: phpmyadmin.k8s0.evoliatis.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpmyadmin-service
                port:
                  number: 32000
  tls:
    - hosts:
      - wordpress.k8s0.evoliatis.fr
      - phpmyadmin.k8s0.evoliatis.fr