apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stress
  name: stress
  labels:
    app: stress
spec:
  selector:
    matchLabels:
      app: stress
  replicas: 1
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: nginx
        image: nginx:1.12
        ports:
        - name: deploy-port
          containerPort: 80        
        resources:
          requests:
            cpu: "250m"
