apiVersion: v1
kind: Service
metadata:
  namespace: stress
  name: nginx-service
  labels:
    app: stress
spec:
  ports:
  - port: 31500
    nodePort: 31500
    targetPort: deploy-port
    protocol: TCP
  selector:
    app: stress
  type: NodePort
