apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  labels:
    app: stress
  namespace: stress
spec:
  hard:
    requests.memory: 64Mi
    requests.cpu: "500m"
    limits.memory: 128Mi
    limits.cpu: "1000m"  
