apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-tcp
spec:
  containers:
  - name: liveness-tcp
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 30
      periodSeconds: 30