apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-local
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
