apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-rules
  namespace: app-wordpress
spec:
  rules:
    - host: wpress.k8s00.evoliatis.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-service
                port:
                  number: 31000
    - host: pma.k8s00.evoliatis.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpmyadmin-service
                port:
                  number: 32000
