apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-cm
data:
  htusers: |
    formation:$2y$05$cHRYBZDOPKZy//LHJtg8qubRYXKeBNeLH.E8i0jTB4b/4KNzqf6CO
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    auth:
      htpasswd:
        realm: basic-realm
        path: /etc/docker/registry/htusers
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
