apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-deployment
  namespace: webservice
  labels:
    app: webservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice
        image: containous/whoami
        ports:
          - name: webservice-port
            containerPort: 80
