apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress-back
  labels:
    app: wordpress
    tier: backend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: backend
    spec:
      containers:
      - image: nazarpc/phpmyadmin
        name: phpmyadmin
        env:
        - name: MYSQL_HOST
          value: wordpress-mysql
        ports:
        - containerPort: 80
          name: phpmyadmin-port
