apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: app-wordpress
  labels:
    app: wordpress
type: Opaque
data:
  # mot de passe : secret
  # echo "secret" | base64
  root-password: c2VjcmV0
  # login/mdp/db : wordpress
  db-name: d29yZHByZXNz
  db-login: d29yZHByZXNz
  db-password: d29yZHByZXNz
