apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-local
  namespace: app-wordpress
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
