apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-local
  namespace: app-wordpress
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
