apiVersion: v1
kind: Service
metadata:
  labels:
    name: minio
  name: minio
  namespace: minio
spec:
  ports:
  - name: api
    nodePort: 30900
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: console
    nodePort: 30901
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: minio
  type: NodePort